export const GET_IMAGE_LIST_REQUEST = "GET_IMAGE_LIST_REQUEST";
export const GET_IMAGE_LIST_SUCCESS = "GET_IMAGE_LIST_SUCCESS";
export const GET_IMAGE_LIST_FAIL = "GET_IMAGE_LIST_FAIL";
export const UPLOAD_IMAGE_REQUEST = "UPLOAD_IMAGE_REQUEST";
export const UPLOAD_IMAGE_SUCCESS = "UPLOAD_IMAGE_SUCCESS";
export const UPLOAD_IMAGE_FAIL = "UPLOAD_IMAGE_FAIL";